### ISSUE TITLE
Body alignement

### ISSUE THREAD

**Issue by asya-sou** [asya-sou/CSCI39548-assignement1#16]
need to adjust the body not to overlap with navbar, pls help

**Comment by Saqifur-Rahman** [comment]
Were you able to correct this Asya/Ivan? Looks to me like there's no overlap between the two currently.

**Comment by asya-sou** [comment]
![image](https://user-images.githubusercontent.com/72818908/120561433-85300f80-c3d2-11eb-8a63-2478728b7d37.png)
there is on my end, I think it just needs like 70 px top margins, I just can't get back to it till night 

My problem is that 70 px margin may mess with phones or tablets?...

**Comment by Saqifur-Rahman** [comment]
Was able to view in maximized/minimized browser without issues on my end. Especially with the newer homepage. I'm comfortable closing the issue if it's resolved on your end too.

**Comment by asya-sou** [comment]
website style is changed, no longer relevant
